USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS RSS_AGENT_DEMO_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE ROLE IF NOT EXISTS RSS_AGENT_DEMO_USER_ROLE;
CREATE DATABASE IF NOT EXISTS RSS_AGENT_DEMO_DB;
CREATE SCHEMA IF NOT EXISTS RSS_AGENT_DEMO_DB.BANKING;
CREATE SCHEMA IF NOT EXISTS RSS_AGENT_DEMO_DB.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS RSS_AGENT_DEMO_DB.AGENT;
CREATE SCHEMA IF NOT EXISTS RSS_AGENT_DEMO_DB.TOOLS;
CREATE DATABASE IF NOT EXISTS RSS_AGENT_SANDBOX_DB;
CREATE SCHEMA IF NOT EXISTS RSS_AGENT_SANDBOX_DB.WORK;

CREATE OR REPLACE TABLE RSS_AGENT_DEMO_DB.BANKING.CUSTOMER (
  CUSTOMER_ID VARCHAR, CUSTOMER_NAME VARCHAR, RISK_RATING VARCHAR);
INSERT INTO RSS_AGENT_DEMO_DB.BANKING.CUSTOMER VALUES
('CUST-1001','Ananya Rao','LOW'),('CUST-1002','Rohan Mehta','MEDIUM'),('CUST-1003','Meera Iyer','HIGH');

CREATE OR REPLACE TABLE RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION (
  TRANSACTION_ID VARCHAR, CUSTOMER_ID VARCHAR, AMOUNT NUMBER(12,2), TRANSACTION_TYPE VARCHAR, STATUS VARCHAR);
INSERT INTO RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION VALUES
('TXN-9001','CUST-1001',12500,'TRANSFER','COMPLETED'),
('TXN-9002','CUST-1001',3200,'PURCHASE','COMPLETED'),
('TXN-9003','CUST-1002',48000,'TRANSFER','COMPLETED'),
('TXN-9004','CUST-1003',95000,'TRANSFER','REVIEW');

CREATE OR REPLACE TABLE RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES (
  NOTE_ID NUMBER, CUSTOMER_ID VARCHAR, NOTE_TEXT VARCHAR, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

GRANT USAGE ON WAREHOUSE RSS_AGENT_DEMO_WH TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON DATABASE RSS_AGENT_DEMO_DB TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON SCHEMA RSS_AGENT_DEMO_DB.BANKING TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA RSS_AGENT_DEMO_DB.BANKING TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON DATABASE RSS_AGENT_SANDBOX_DB TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON SCHEMA RSS_AGENT_SANDBOX_DB.WORK TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA RSS_AGENT_SANDBOX_DB.WORK TO ROLE RSS_AGENT_DEMO_USER_ROLE;

SELECT COUNT(*) AS CUSTOMER_COUNT FROM RSS_AGENT_DEMO_DB.BANKING.CUSTOMER;
SELECT COUNT(*) AS TRANSACTION_COUNT FROM RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION;
