USE ROLE RSS_AGENT_DEMO_USER_ROLE;
USE WAREHOUSE RSS_AGENT_DEMO_WH;
UPDATE RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION SET STATUS='MANUAL_REVIEW' WHERE TRANSACTION_ID='TXN-9002';
SELECT TRANSACTION_ID,STATUS FROM RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION WHERE TRANSACTION_ID='TXN-9002';
UPDATE RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION SET STATUS='COMPLETED' WHERE TRANSACTION_ID='TXN-9002';
INSERT INTO RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES (NOTE_ID,CUSTOMER_ID,NOTE_TEXT) VALUES (101,'CUST-1001','RBAC baseline test');
SELECT * FROM RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES WHERE NOTE_ID=101;
DELETE FROM RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES WHERE NOTE_ID=101;
