USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE PROCEDURE RSS_AGENT_DEMO_DB.TOOLS.UPDATE_BANKING_STATUS(P_TRANSACTION_ID VARCHAR,P_STATUS VARCHAR)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS CALLER AS $$
BEGIN
  UPDATE RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION SET STATUS=:P_STATUS WHERE TRANSACTION_ID=:P_TRANSACTION_ID;
  RETURN 'BANKING STATUS UPDATED';
END;
$$;

CREATE OR REPLACE PROCEDURE RSS_AGENT_DEMO_DB.TOOLS.ADD_AGENT_NOTE(P_NOTE_ID NUMBER,P_CUSTOMER_ID VARCHAR,P_NOTE_TEXT VARCHAR)
RETURNS VARCHAR LANGUAGE SQL EXECUTE AS CALLER AS $$
BEGIN
  INSERT INTO RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES(NOTE_ID,CUSTOMER_ID,NOTE_TEXT)
  VALUES(:P_NOTE_ID,:P_CUSTOMER_ID,:P_NOTE_TEXT);
  RETURN 'AGENT NOTE CREATED';
END;
$$;

GRANT USAGE ON SCHEMA RSS_AGENT_DEMO_DB.TOOLS TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON PROCEDURE RSS_AGENT_DEMO_DB.TOOLS.UPDATE_BANKING_STATUS(VARCHAR,VARCHAR) TO ROLE RSS_AGENT_DEMO_USER_ROLE;
GRANT USAGE ON PROCEDURE RSS_AGENT_DEMO_DB.TOOLS.ADD_AGENT_NOTE(NUMBER,VARCHAR,VARCHAR) TO ROLE RSS_AGENT_DEMO_USER_ROLE;
