USE ROLE ACCOUNTADMIN;
SELECT TRANSACTION_ID,CUSTOMER_ID,AMOUNT,TRANSACTION_TYPE,STATUS
FROM RSS_AGENT_DEMO_DB.BANKING.BANK_TRANSACTION WHERE TRANSACTION_ID='TXN-9002';
SELECT NOTE_ID,CUSTOMER_ID,NOTE_TEXT,CREATED_AT
FROM RSS_AGENT_SANDBOX_DB.WORK.AGENT_NOTES WHERE NOTE_ID=401;

-- Version/edition-sensitive lineage validation.
SELECT * FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE(
  'RSS_AGENT_DEMO_DB.AGENT.BANKING_RSS_AGENT','CORTEX_AGENT','UPSTREAM'));

SELECT query_id,start_time,user_name,role_name,query_text,agent_type,execution_status,error_code,error_message
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE start_time>=DATEADD('hour',-2,CURRENT_TIMESTAMP()) AND agent_type IS NOT NULL
ORDER BY start_time DESC;

SELECT query_id,query_start_time,user_name,direct_objects_accessed,base_objects_accessed,agents_info
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE query_start_time>=DATEADD('hour',-2,CURRENT_TIMESTAMP()) AND agents_info IS NOT NULL
ORDER BY query_start_time DESC;
