USE ROLE ACCOUNTADMIN;
-- Review before executing. This removes the demo objects.
DROP DATABASE IF EXISTS RSS_AGENT_SANDBOX_DB;
DROP DATABASE IF EXISTS RSS_AGENT_DEMO_DB;
DROP WAREHOUSE IF EXISTS RSS_AGENT_DEMO_WH;
DROP ROLE IF EXISTS RSS_AGENT_DEMO_USER_ROLE;
